### ISSUE TITLE
Support for API client ratelimit flags

### ISSUE THREAD

**Issue by Agalin** [Alkemic/linkerd-cert-manager-identity#2]
Latest version of the official identity component supports configuring rate limits for the Kubernetes API client. The following flags are used by the official chart:

```
-kube-apiclient-qps=100
-kube-apiclient-burst=200
```

To improve compatibility, at least dummy flags should be added, ideally it would be full rate limit support.

**Comment by Alkemic** [comment]
This and #1 are done in `ghcr.io/alkemic/linkerd-cert-manager-identity:stable-2.14.0`.
